ticker: AAPL
interval: 1d #1h
period: 2y #3mo
seq_length: 24
test_size: 0.2
random_seed: 42
hidden_size: 64
num_layers: 2
lr: 0.001
epochs: 128
future_hours: 8
train_data_path: data/data_train/AAPL_1d_2y.csv
n_recnet: 1000;

features:
  - Close
  - Volume
  - High
  - Low

target_col: 0 # close